lwr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

 # Effort controller----------------------------------
 # joint1_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_0_joint
 # joint2_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_1_joint
 # joint3_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_2_joint
 # joint4_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_3_joint
 # joint5_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_4_joint
 # joint6_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_5_joint
 # joint7_effort_controller:
 #   type: effort_controllers/JointEffortController
 #   joint: lwr_arm_6_joint
